spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinLogDB
    username: postgres
    password: Guitar@600
    platform: postgres
  jpa:
    database: POSTGRESQL
    properties..hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update

application:
  jwt:
    secret: heytherethisisthesecrettosignmytoken