spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinLogDB
    username: postgres
    password: Guitar@600
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate.ddl-auto: update

application:
  jwt:
    secret: heytherethisisthesecrettosignmytoken