spring:
  datasource:
    url: jdbc:h2:mem:financial-logger
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  #http://localhost:8080/h2-console
  h2:
    console.enabled: true