ALTER TABLE FINANCIAL_lOGGER_USER ALTER ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE ROLE ALTER ID INT NOT NULL AUTO_INCREMENT;

--thisismypassword : $2a$10$ZZiLnhScwrB9gcPsLt2rZ.4KGChnyvdIEPZ/c7YXjIuASzcxwVnlC

INSERT INTO FINANCIAL_lOGGER_USER (USERNAME, FIRST_NAME, LAST_NAME, PASSWORD) VALUES ('njoy', 'Naveen', 'Joy', '$2a$10$ZZiLnhScwrB9gcPsLt2rZ.4KGChnyvdIEPZ/c7YXjIuASzcxwVnlC');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1,2);
